name: HelloFlow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Diga oi
        run: echo "Hello World!"
      - name: Diva valeu
        run: echo "Valeu - bye!"
