name: HelloFlow
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Diga oi
        run: echo "Hello World!"
      - name: Diva valeu
        run: echo "Valeu - bye!"
